# Generated by Django 5.2.7 on 2025-10-29 15:12

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SampleSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=20)),
                ('organization', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=100)),
                ('requirements', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to=api.models.upload_submission_file)),
                ('pdf', models.FileField(blank=True, editable=False, null=True, upload_to=api.models.upload_submission_pdf)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
